---
- name: Deploy Apache Website
  hosts: localhost
  become: yes  # Run tasks as root (sudo)
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start and Enable Apache
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Copy website content
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: 0644

    - name: Restart Apache to apply changes
      systemd:
        name: apache2
        state: restarted


